password:
  minimum: 6
avatar:
  size_resize: 400
validates:
  subject_name_max_length: 20
  subject_description_max_length: 40
paginate:
  subjects_per_page: 10
  users_per_page: 10
batch_job:
  assign_to_course: 1
  reject_from_course: 2
  daily: 1
  mail_from: "quangblackhat@gmail.com"
